spring:
  aplication:
    name: Fiskenatet
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MYSQLInnoDBDialect
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
      ddl-auto: update
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/fiskenatet?useSSL=false
    username: root
    password: assassin723




  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  context-path: /api

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR
    com.example.fiskenatet: INFO
